changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} on {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* [#{{.Custom.Issue}}](https://github.com/miniscruff/changie/issues/{{.Custom.Issue}}) {{.Body}}'
kinds:
  - label: Added
    auto: minor
  - label: Changed
    auto: major
  - label: Deprecated
    auto: minor
  - label: Removed
    auto: minor # temporarily consider removed a minor change
  - label: Fixed
    auto: patch
  - label: Security
    auto: patch
newlines:
  afterChangelogHeader: 1
  afterKind: 1
  afterChangelogVersion: 1
  beforeKind: 1
  endOfVersion: 1
custom:
- key: Issue
  type: int
  minInt: 1
replacements:
- path: 'docs/config.toml'
  find: "  version = '.*"
  replace: "  version = '{{.Version}}'"
- path: 'docs/version.json'
  find: '    "latest": ".*"'
  replace: '    "latest": "{{.Version}}"'
- path: package.json
  find: '  "version": ".*",'
  replace: '  "version": "{{.VersionNoPrefix}}",'
