# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changie < Formula
  desc "Automated changelog tool for preparing releases with lots of customization options."
  homepage "https://changie.dev"
  version "1.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/miniscruff/changie/releases/download/v1.10.1/changie_1.10.1_darwin_arm64.tar.gz"
      sha256 "26a65b871034cecadeae8e0a6ca1c721364595631dc5dc9b530786a1826fb33a"

      def install
        bin.install "changie"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/miniscruff/changie/releases/download/v1.10.1/changie_1.10.1_darwin_amd64.tar.gz"
      sha256 "f5ae33fcc64bfe4a78e7353125ac9bf2408ae691c91e23a03df9864548e057ed"

      def install
        bin.install "changie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/miniscruff/changie/releases/download/v1.10.1/changie_1.10.1_linux_amd64.tar.gz"
      sha256 "58f1b65322fc2f7e3153332fe521c3bc7d89da403b8367fe7666cb09cc0e66e9"

      def install
        bin.install "changie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/miniscruff/changie/releases/download/v1.10.1/changie_1.10.1_linux_arm64.tar.gz"
      sha256 "e9760c6871e2f025e16840b99250275e7effcd9c81bc0876eca4c2288108e483"

      def install
        bin.install "changie"
      end
    end
  end
end
