# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changie < Formula
  desc "Automated changelog tool for preparing releases with lots of customization options."
  homepage "https://changie.dev"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miniscruff/changie/releases/download/v1.5.0/changie_1.5.0_darwin_amd64.tar.gz"
      sha256 "022f12b3287397593d2c88b9bd7f51acf2a07d2548e5dac2d8427c3605de421c"

      def install
        bin.install "changie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miniscruff/changie/releases/download/v1.5.0/changie_1.5.0_darwin_arm64.tar.gz"
      sha256 "a1c793b421930de2bf8a8d064cd2a8d69e031b550056e299ac3057bb9d38ebf5"

      def install
        bin.install "changie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/miniscruff/changie/releases/download/v1.5.0/changie_1.5.0_linux_arm64.tar.gz"
      sha256 "5a4424423f9e96c37d67dc812721f6fb61bc37b411667df5c483c62ef8cd8d54"

      def install
        bin.install "changie"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/miniscruff/changie/releases/download/v1.5.0/changie_1.5.0_linux_amd64.tar.gz"
      sha256 "09c4b702cf1b11798d498e6f63c55f618432bf859bb654e5ab8b5bc114f3a880"

      def install
        bin.install "changie"
      end
    end
  end
end
