# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changie < Formula
  desc "Automated changelog tool for preparing releases with lots of customization options."
  homepage "https://changie.dev"
  version "1.22.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miniscruff/changie/releases/download/v1.22.0/changie_1.22.0_darwin_amd64.tar.gz"
      sha256 "b3c5f583f64db42b31df61b77147922a7a141cc13c80db2edf59da893e0f1aa4"

      def install
        bin.install "changie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miniscruff/changie/releases/download/v1.22.0/changie_1.22.0_darwin_arm64.tar.gz"
      sha256 "81f9eb0ef03662c3ba8a82f58901af57d50817eb9a2068ab2750b003ec106b2b"

      def install
        bin.install "changie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/miniscruff/changie/releases/download/v1.22.0/changie_1.22.0_linux_amd64.tar.gz"
      sha256 "e4fb7126f8cd4db49503daf3105e255f3c005077239098b1c84da6ed62fb4ef0"
      def install
        bin.install "changie"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/miniscruff/changie/releases/download/v1.22.0/changie_1.22.0_linux_arm64.tar.gz"
      sha256 "9fac10c2c33253439edae15a02d64e133a649e45b4a03b2a4ada7424320c581a"
      def install
        bin.install "changie"
      end
    end
  end
end
