# Configure all our settings
Set FontSize 20
Set Width 800
Set Height 600
Set TypingSpeed 50ms
Set Theme "Catppuccin Mocha"
Set Padding 8

Output hide.gif

Type "go run main.go new --dry-run"
Sleep 1s
Enter
Sleep 1s

Type "j"
Sleep 1s
Type "j"
Sleep 1s
Type "j"
Sleep 1s
Type "j"
Sleep 1s
Type "k"
Sleep 1s
Type "k"
Sleep 1s
Type "k"
Sleep 1s
Enter
Sleep 1s

Type "asdf"
Sleep 1s
Enter
Sleep 1s

Type "asdf"
Sleep 1s
Enter

