# https://taskfile.dev
version: '3'

tasks:
  test:
    desc: Run unit tests
    cmds:
      - go test -coverprofile=c.out ./...

  coverage:
    desc: Run unit tests and code coverage
    cmds:
      - task: test
      - go tool cover -html=c.out

  watch:
    desc: Run unit tests and rerun on file changes with ginkgo
    cmds:
      - ginkgo watch ./...

  lint:
    desc: Run lint checks with golangci
    cmds:
      - golangci-lint run ./...

  format:
    desc: Run auto formatters
    cmds:
      - gofmt -s -w .
      - goimports -w -local github.com/miniscruff/changie .

  docs-serve:
    desc: Serve documentation
    cmds:
      - hugo serve -s website

  docs-build:
    desc: Build documentation
    cmds:
      - hugo -s website --minify --gc
