name: Generate release pull request

on:
  issue_comment:
    types: [created]

jobs:
  # This job only runs for pull request comments
  pr-changie-work:
    name: PR comment
    if: "${{ github.event.issue.pull_request && startsWith(github.event.issue_comment.comment.body, '/changie')}}"
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Check out code
      uses: actions/checkout@v4

    - name: Run changie
      env:
        COMMENT: "${{ github.event.issue_comment.comment.body }}"
      run: |
        export CMD=$(echo $COMMENT | cut -c10-)
        go run main.go ${CMD}
        echo $CMD
        git status

        # - name: Create Pull Request
        # uses: peter-evans/create-pull-request@v5
        # with:
        # commit-message: Ran changie from comment

