name: npm publish test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Setup NPM
      uses: actions/setup-node@v6
      with:
        node-version: '24.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Ensure npm supports trusted publishing
      run: npm install -g npm@latest

    - name: Unpublish throwaway test version
      run: npm unpublish changie@1.25.2-beta.0 --force
