name: vhs

on:
  pull_request:
    branches: [ main ]
    paths:
    - 'examples/**.tape'
jobs:
  vhs:
    runs-on: ubuntu-20.04
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: charmbracelet/vhs-action@v1
        name: 'install vhs'
      - name: 'build tape files'
        run: |
          cd examples
          vhs getting_started.tape
          vhs custom_prompts.tape
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update generated VHS GIF
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: '*.gif *.webm'
