name: vhs auto commit

on:
  pull_request:
    branches: [ main ]
    paths:
    - '.github/tape-auto-commit.yml' # temp to run the command again
    - 'examples/**.tape'
jobs:

  vhs:
    name: vhs auto commit
    runs-on: ubuntu-20.04
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: build getting started
      uses: charmbracelet/vhs-action@v1
      with:
        path: 'examples/getting_started.tape'

    - name: build custom prompts
      uses: charmbracelet/vhs-action@v1
      with:
        path: 'examples/custom_prompts.tape'

    - name: commit new recordings
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update generated VHS GIF
        commit_user_name: vhs-action
        commit_user_email: actions@github.com
        commit_author: vhs-action <actions@github.com>
        file_pattern: '*.gif *.webm'
